<?xml version='1.0' standalone='yes'?>
<config>
<version>0.7.0</version>
<admin_name>admin</admin_name>
<admin_pass>d41d8cd98f00b204e9800998ecf8427e</admin_pass>
<host>127.0.0.1</host>
<port>62656</port>
<pass></pass>
<output>1</output>
<template>default</template>
<language>hu</language>
<volume>100</volume>
<repeat></repeat>
<random></random>
<fade>5</fade>
<rights>
<add_songs>selected</add_songs>
<start_playing>selected</start_playing>
<pause_playing>selected</pause_playing>
<set_volume>selected</set_volume>
<controll_playlist>selected</controll_playlist>
<controll_player>selected</controll_player>
<admin_relaxx></admin_relaxx>
<admin_mpd></admin_mpd>
</rights>
<plcolumns>Pos:Artist:Title:Album:Genre:Time</plcolumns>
<trcolumns>Artist:Title:Genre:Time</trcolumns>
<configfile>/config/config.php</configfile>
</config>
